// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://infresxpaglulwiooanc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZnJlc3hwYWdsdWx3aW9vYW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MDIxODcsImV4cCI6MjA4NjA3ODE4N30.iYNG6N2aMOuIPpTaTY7YHoR8rycv97AWxYlyYd43SJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});